// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdujajonwfwrdgkfdqgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkdWpham9ud2Z3cmRna2ZkcWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTA3MzUsImV4cCI6MjA2MDk2NjczNX0.6_27qt0PH0Lz__7xxNUaHzhX9SEDbRw12d2b9xf_SEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);